jwt:
  secret: usersecret
spring:
  datasource:
    password: ''
    url: jdbc:h2:mem:teste
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true